### ISSUE TITLE
maven dependencies correct?

### ISSUE THREAD

**Issue by RobPodolski** [findify/s3mock#1]
Hi - I get the following when trying to start the api using java....

        S3Mock api = S3Mock.create(8001, "/tmp/s3");
        api.start();

Looks like "RoutingSettings" missing from akka-http-core-experimental_2.11?

Rob

[sqsmock-akka.actor.default-dispatcher-4] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
Exception in thread "main" java.lang.NoClassDefFoundError: akka/http/scaladsl/settings/RoutingSettings$
	at io.findify.s3mock.S3Mock.start(S3Mock.scala:137)
	at com.elsevier.agrm.sc.articleUpdate.sqs.MockS3Server.main(MockS3Server.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: akka.http.scaladsl.settings.RoutingSettings$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by shuttie** [comment]
I cannot reproduce this issue: created empty maven project, dropped s3mock there as a dependency and it was able to start successfully. Can you please post your full pom.xml (or at least the dependencies section)? It might be some sort of dependency conflict.

**Comment by RobPodolski** [comment]
Hi
and thanks for getting back to me.  Sorry it took a while - had to reinstate the project etc..  Here's the parts of the POM you asked about.
<repositories>
    <repository>
        <id>findify</id>
        <url>https://dl.bintray.com/findify/maven/</url>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk</artifactId>
    </dependency>
    <dependency>
        <groupId>org.elasticmq</groupId>
        <artifactId>elasticmq-rest-sqs_2.11</artifactId>
        <version>0.9.3</version>
    </dependency>

    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>1.7.21</version>
    </dependency>


    <dependency>
        <groupId>commons-configuration</groupId>
        <artifactId>commons-configuration</artifactId>
        <version>1.6</version>
    </dependency>

    <dependency>
        <groupId>io.findify</groupId>
        <artifactId>s3mock_2.11</artifactId>
        <version>0.1.0</version>
        <exclusions>
            <exclusion>
                <groupId>com.typesafe.akka</groupId>
                <artifactId>akka-http-core-experimental_2.11</artifactId>
            </exclusion>
        </exclusions>
    </dependency>


    <dependency>
        <groupId>org.apache.solr</groupId>
        <artifactId>solr-solrj</artifactId>
        <version>${solr.version}</version>
    </dependency>

</dependencies>

**Comment by shuttie** [comment]
I see the problem in this snippet:

    <dependency>
        <groupId>io.findify</groupId>
        <artifactId>s3mock_2.11</artifactId>
        <version>0.1.0</version>
        <exclusions>
            <exclusion>
                <groupId>com.typesafe.akka</groupId>
                <artifactId>akka-http-core-experimental_2.11</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

Suggestions:
* Do not exclude `akka-http-core-experimental` dependency as it contains the missing `akka.http.scaladsl.settings.RoutingSettings` class
* try the latest 0.1.2 version, it has some bugs fixed

**Comment by RobPodolski** [comment]
Thanks - for the suggestion - will try the 0.1.2 version.  NB I put the exclusion in myself in an attempt to fix the problem since it was a class within this module that seemed to be the problem.  Sorry - should have removed this before sending to you.

**Comment by RobPodolski** [comment]
Unfortunately it still gives the error message.  Maybe there's a problem with my using Java 8? 
Here's the POM...
<repositories>
    <repository>
        <id>findify</id>
        <url>https://dl.bintray.com/findify/maven/</url>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk</artifactId>
    </dependency>
    <dependency>
        <groupId>org.elasticmq</groupId>
        <artifactId>elasticmq-rest-sqs_2.11</artifactId>
        <version>0.9.3</version>
    </dependency>

    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>1.7.21</version>
    </dependency>


    <dependency>
        <groupId>commons-configuration</groupId>
        <artifactId>commons-configuration</artifactId>
        <version>1.6</version>
    </dependency>

    <dependency>
        <groupId>io.findify</groupId>
        <artifactId>s3mock_2.11</artifactId>
        <version>0.1.2</version>
    </dependency>


    <dependency>
        <groupId>org.apache.solr</groupId>
        <artifactId>solr-solrj</artifactId>
        <version>${solr.version}</version>
    </dependency>

</dependencies>Here's the code...
S3Mock api = S3Mock.create(8001, "/tmp/s3");
api.start();
AmazonS3Client s3Client = new AmazonS3Client();
s3Client.setEndpoint("http://127.0.0.1:8001");Here's the stack trace...
/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin/java -Didea.launcher.port=7537 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 15 CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/lib/tools.jar:/Users/podolskir/scopus-search/scopus-article-update-tests/target/classes:/Users/podolskir/.m2/repository/com/amazonaws/aws-java-sdk/1.7.0/aws-java-sdk-1.7.0.jar:/Users/podolskir/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/podolskir/.m2/repository/org/apache/httpcomponents/httpclient/4.5.1/httpclient-4.5.1.jar:/Users/podolskir/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar:/Users/podolskir/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.1.1/jackson-core-2.1.1.jar:/Users/podolskir/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.1.1/jackson-databind-2.1.1.jar:/Users/podolskir/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.1.1/jackson-annotations-2.1.1.jar:/Users/podolskir/.m2/repository/joda-time/joda-time/2.9.4/joda-time-2.9.4.jar:/Users/podolskir/.m2/repository/org/elasticmq/elasticmq-rest-sqs_2.11/0.9.3/elasticmq-rest-sqs_2.11-0.9.3.jar:/Users/podolskir/.m2/repository/org/scala-lang/scala-library/2.11.8/scala-library-2.11.8.jar:/Users/podolskir/.m2/repository/org/elasticmq/elasticmq-core_2.11/0.9.3/elasticmq-core_2.11-0.9.3.jar:/Users/podolskir/.m2/repository/org/joda/joda-convert/1.8.1/joda-convert-1.8.1.jar:/Users/podolskir/.m2/repository/org/scala-lang/modules/scala-xml_2.11/1.0.5/scala-xml_2.11-1.0.5.jar:/Users/podolskir/.m2/repository/com/typesafe/akka/akka-actor_2.11/2.3.15/akka-actor_2.11-2.3.15.jar:/Users/podolskir/.m2/repository/com/typesafe/config/1.2.1/config-1.2.1.jar:/Users/podolskir/.m2/repository/com/typesafe/akka/akka-slf4j_2.11/2.3.15/akka-slf4j_2.11-2.3.15.jar:/Users/podolskir/.m2/repository/com/typesafe/akka/akka-http-experimental_2.11/2.0.4/akka-http-experimental_2.11-2.0.4.jar:/Users/podolskir/.m2/repository/com/typesafe/akka/akka-http-core-experimental_2.11/2.0.4/akka-http-core-experimental_2.11-2.0.4.jar:/Users/podolskir/.m2/repository/com/typesafe/akka/akka-parsing-experimental_2.11/2.0.4/akka-parsing-experimental_2.11-2.0.4.jar:/Users/podolskir/.m2/repository/com/typesafe/akka/akka-stream-experimental_2.11/2.0.4/akka-stream-experimental_2.11-2.0.4.jar:/Users/podolskir/.m2/repository/org/scala-lang/modules/scala-async_2.11/0.9.5/scala-async_2.11-0.9.5.jar:/Users/podolskir/.m2/repository/com/typesafe/scala-logging/scala-logging_2.11/3.1.0/scala-logging_2.11-3.1.0.jar:/Users/podolskir/.m2/repository/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar:/Users/podolskir/.m2/repository/org/slf4j/slf4j-simple/1.7.21/slf4j-simple-1.7.21.jar:/Users/podolskir/.m2/repository/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.jar:/Users/podolskir/.m2/repository/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar:/Users/podolskir/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar:/Users/podolskir/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/Users/podolskir/.m2/repository/commons-digester/commons-digester/1.8/commons-digester-1.8.jar:/Users/podolskir/.m2/repository/commons-beanutils/commons-beanutils/1.8.3/commons-beanutils-1.8.3.jar:/Users/podolskir/.m2/repository/commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0.jar:/Users/podolskir/.m2/repository/io/findify/s3mock_2.11/0.1.2/s3mock_2.11-0.1.2.jar:/Users/podolskir/.m2/repository/com/typesafe/akka/akka-stream_2.11/2.4.9/akka-stream_2.11-2.4.9.jar:/Users/podolskir/.m2/repository/com/typesafe/ssl-config-akka_2.11/0.2.1/ssl-config-akka_2.11-0.2.1.jar:/Users/podolskir/.m2/repository/com/typesafe/ssl-config-core_2.11/0.2.1/ssl-config-core_2.11-0.2.1.jar:/Users/podolskir/.m2/repository/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar:/Users/podolskir/.m2/repository/org/reactivestreams/reactive-streams/1.0.0/reactive-streams-1.0.0.jar:/Users/podolskir/.m2/repository/com/github/pathikrit/better-files_2.11/2.16.0/better-files_2.11-2.16.0.jar:/Users/podolskir/.m2/repository/org/apache/solr/solr-solrj/5.3.0/solr-solrj-5.3.0.jar:/Users/podolskir/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/podolskir/.m2/repository/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar:/Users/podolskir/.m2/repository/org/apache/httpcomponents/httpmime/4.4.1/httpmime-4.4.1.jar:/Users/podolskir/.m2/repository/org/apache/zookeeper/zookeeper/3.4.6/zookeeper-3.4.6.jar:/Users/podolskir/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar:/Users/podolskir/.m2/repository/org/codehaus/woodstox/woodstox-core-asl/4.4.1/woodstox-core-asl-4.4.1.jar:/Users/podolskir/.m2/repository/org/noggit/noggit/0.6/noggit-0.6.jar:/Applications/IntelliJ IDEA 15 CE.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain com.elsevier.agrm.sc.articleUpdate.mockaws.VerifyFakeS3[sqsmock-akka.actor.default-dispatcher-3] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger startedException in thread "main" java.lang.NoClassDefFoundError: akka/http/scaladsl/server/PathMatchers$RemainingPath$ at io.findify.s3mock.S3Mock.start(S3Mock.scala:36) at com.elsevier.agrm.sc.articleUpdate.mockaws.VerifyFakeS3.main(VerifyFakeS3.java:60) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)Caused by: java.lang.ClassNotFoundException: akka.http.scaladsl.server.PathMatchers$RemainingPath$ at java.net.URLClassLoader.findClass(URLClassLoader.java:381) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ... 7 more

**Comment by shuttie** [comment]
Thanks for the info, I was able to reproduce the issue, but with the bad news for you:
* s3mock has akka-http-2.4 dependency (it's a core one, used for the REST API)
* elasticmq uses akka-http 1.0 dependency (which is quite an old version which is absolutely incompatible with 2.4)

So you have a dependency conflict and I have no idea how to fix it. You can create a ticket for https://github.com/adamw/elasticmq to ask Adam to upgrade elasticmq to akka-http 2.4 (as I'm not sure that it's possible to downgrade s3mock to akka-http 1.0).

**Comment by RobPodolski** [comment]
Many thanks for the info - will think about this!
