### ISSUE TITLE
Problem with maven-enforcer-plugin in 0.1.4 version

### ISSUE THREAD

**Issue by rbenitez** [findify/s3mock#14]
Hello, I'm trying to use your library in 0.1.4 version, but I have a problem with maven-enforcer-plugin.

When I try to install the project, I got: 

> Dependency
> convergence error for com.typesafe:config:1.2.1 paths to dependency are:

>   +-io.findify:s3mock_2.11:0.1.4
>     +-com.typesafe.akka:akka-stream_2.11:2.4.11
>       +-com.typesafe.akka:akka-actor_2.11:2.3.4
>         +-com.typesafe:config:1.2.1
> and
>   +-io.findify:s3mock_2.11:0.1.4
>     +-com.typesafe.akka:akka-stream_2.11:2.4.11
>       +-com.typesafe:ssl-config-akka_2.11:0.2.1
>         +-com.typesafe:ssl-config-core_2.11:0.2.1
>           +-com.typesafe:config:1.2.0
> 
> [WARNING]
> Dependency convergence error for org.scala-lang:scala-library:2.11.8 paths to dependency are:
>   +-io.findify:s3mock_2.11:0.1.4
>     +-org.scala-lang:scala-library:2.11.8
> and
>   +-io.findify:s3mock_2.11:0.1.4
>     +-com.typesafe.akka:akka-stream_2.11:2.4.11
>       +-org.scala-lang:scala-library:2.11.8
> and
>   +-io.findify:s3mock_2.11:0.1.4
>     +-com.typesafe.akka:akka-stream_2.11:2.4.11
>       +-com.typesafe.akka:akka-actor_2.11:2.3.4
>         +-org.scala-lang:scala-library:2.11.1`
> 

Like you can see, com.typesafe:config has two versions different 1.2.0 and 1.2.1.

Could you fix this problem with the dependencies?

Thank you so much.

**Comment by shuttie** [comment]
Try now with 0.1.5, the issue might walk away. It's hard to diagnose/reproduce this issue without having a complete pom.xml (at least the part with dependencies, as I guess there's a conflict there).

**Comment by rbenitez** [comment]
HI @shuttie. 

I continue with the problem when I use maven-enforcer-plugin, so I have removed the _maven-enforcer-plugin_ plugin, but now I have got another problem:

>  **java.lang.NoClassDefFoundError: akka/japi/function/Function**
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at akka.stream.Supervision$.<init>(Supervision.scala:57)
> 	at akka.stream.Supervision$.<clinit>(Supervision.scala)
> 	at akka.stream.ActorMaterializerSettings$.apply(ActorMaterializer.scala:242)
> 	at akka.stream.ActorMaterializerSettings$.apply(ActorMaterializer.scala:232)
> 	at akka.stream.ActorMaterializer$$anonfun$1.apply(ActorMaterializer.scala:41)
> 	at akka.stream.ActorMaterializer$$anonfun$1.apply(ActorMaterializer.scala:41)
> 	at scala.Option.getOrElse(Option.scala:121)
> 	at akka.stream.ActorMaterializer$.apply(ActorMaterializer.scala:41)
> 	at io.findify.s3mock.S3Mock.start(S3Mock.scala:33
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
> 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
> 	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
> Caused by: java.lang.ClassNotFoundException: akka.japi.function.Function
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 47 more


I'm using Java 8. 

Do know which could be the problem?

Thanks in advance

**Comment by shuttie** [comment]
You definitely have some sort of dependency conflict. So there are my questions:

* Can you provide your pom.xml (at least the part with the dependencies)?
* Which version of s3mock do you use?
* How can it happen that you have akka-actor-2.3 and akka-stream-2.4 mixed together in the same classpath? Akka-stream-2.4 can only be used with akka-actor-2.4. 

So I see it as an issue of your application dependencies list, not s3mock. Maybe you're using some old version of elasticmq to mock SQS or something.

**Comment by rbenitez** [comment]
Hi, please check this picture. Here you can see like akka-actor is 2.3.4 and akka-stream 2.4 :( 

![screen shot 2016-12-07 at 8 58 44 am](https://cloud.githubusercontent.com/assets/1333445/20959514/9e78ad5e-bc5b-11e6-93d1-df597bcfb6c3.png)

Thanks

**Comment by rbenitez** [comment]
Hi again, 

finally we can fix the problem adding "dependencyManagement" in our pom:

```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-core</artifactId>
                <version>1.11.63</version>
            </dependency>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-s3</artifactId>
                <version>1.11.63</version>
            </dependency>
            <dependency>
                <groupId>com.typesafe.akka</groupId>
                <artifactId>akka-actor_2.11</artifactId>
                <version>2.4.14</version>
            </dependency>
            <dependency>
                <groupId>com.typesafe.akka</groupId>
                <artifactId>akka-parsing_2.11</artifactId>
                <version>10.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.typesafe.akka</groupId>
                <artifactId>akka-stream_2.11</artifactId>
                <version>2.4.14</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

Thanks you.
