### ISSUE TITLE
Bind to random port and get it's number

### ISSUE THREAD

**Issue by jimirocks** [findify/s3mock#18]
Currently it seems it's possible to bind to random port setting port to `0` however there is no way to get that port number back in order to connect it.

This would be handy when running in some CI systems where one cannot rely on fixed port to be free.

**Comment by reikje** [comment]
Could you use

```
import java.net.ServerSocket
val free = new ServerSocket(0).getLocalPort
val api = S3Mock(port = free, dir = "/tmp/s3")
```

**Comment by jimirocks** [comment]
that is clever workaround, but I believe it would be better to create initialize the port in the same place where is bound.

**Comment by reikje** [comment]
What do you want to do exactly? Asking the developer to specify a port is very flexible. So you can pick any free port on your machine, i.e. by using the code above or by using your cluster manager / scheduler to give you a free port.

**Comment by schoeneu** [comment]
@jimirocks  In s3mock 0.1.6 and above (maybe in previous versions, I haven't checked), `S3Mock::start` returns an instance of `akka.http.scaladsl.Http.ServerBinding`.
That means you should be able set it to port 0 when creating the mock and then extract the port as follows, no?

```java
s3Mock = S3Mock.create(0, "/tmp/somefolder");
Http.ServerBinding binding = s3Mock.start();
port = binding.localAddress().getPort();
```

**Comment by jimirocks** [comment]
@schoeneu sorry for slow reaction, yep this works and is sufficient
