### ISSUE TITLE
JAVA example failure, AWSCredentials related

### ISSUE THREAD

**Issue by jethrolam** [findify/s3mock#2]
I tried your JAVA example.  The target file '/tmp/s3/testbucket/file/name' was created but it has no content:

    [INFO] [08/19/2016 03:56:28.349] [sqsmock-akka.actor.default-dispatcher-3][akka.actor.ActorSystemImpl(sqsmock)] request: HttpRequest(HttpMethod(PUT),http://127.0.0.1:8001/testbucket/,List(Host: 127.0.0.1:8001, user-agent: aws-sdk-java/1.11.15 Mac_OS_X/10.11.6 Java_HotSpot(TM)_64-Bit_Server_VM/25.45-b02/1.8.0_45, amz-sdk-invocation-id: ac7dd0da-5eed-2f2c-94dc-b17ab7cccb20, amz-sdk-retry: 0/0/500, Connection: Keep-Alive, Timeout-Access: <function1>),HttpEntity.Strict(application/octet-stream,ByteString()),HttpProtocol(HTTP/1.1))
     2016-08-19 03:56:28.454 [sqsmock-akka.actor.default-dispatcher-3] TEST DEBUG i.f.s.provider.FileProvider - crating bucket testbucket
    [INFO] [08/19/2016 03:56:28.531] [sqsmock-akka.actor.default-dispatcher- [akka.actor.ActorSystemImpl(sqsmock)] request: HttpRequest(HttpMethod(PUT),http://127.0.0.1:8001/testbucket/file/name,List(Host: 127.0.0.1:8001, user-agent: aws-sdk-java/1.11.15 Mac_OS_X/10.11.6 Java_HotSpot(TM)_64-Bit_Server_VM/25.45-b02/1.8.0_45, amz-sdk-invocation-id: 1e6f40c7-3d9c-bed2-ec74-d0b75c41b8ae, amz-sdk-retry: 0/0/500, Connection: Keep-Alive, Expect: 100-continue, Timeout-Access: <function1>),HttpEntity.Default(text/plain; charset=UTF-8,8 bytes total),HttpProtocol(HTTP/1.1))
    2016-08-19 03:56:28.571 [sqsmock-akka.actor.default-dispatcher-3] TEST DEBUG i.f.s.provider.FileProvider - writing file for s3://testbucket/file/name to /tmp/s3/testbucket/file/name, bytes = 0

bytes = 0 according to log

**Comment by jethrolam** [comment]
FYI Problem resolved by replacing
    AmazonS3Client client = new AmazonS3Client(new AnonymousAWSCredentials());
with 
    AmazonS3Client client = new AmazonS3Client(new BasicAWSCredentials("hello", "world"));

**Comment by shuttie** [comment]
Thanks for the bugreport, fixed in https://github.com/findify/s3mock/commit/48636a0a70759157452107d7d026932d37d600b2 (see version 0.1.1)
