### ISSUE TITLE
copyObject throws exception when destinationKey contains folder that does not exist

### ISSUE THREAD

**Issue by anaida-gasparyan** [findify/s3mock#21]
Code:
```java
s3Client.createBucket("bucket-1");
s3Client.createBucket("bucket-2");

PutObjectResult putObjectResult = s3Client.putObject("bucket-1", "test.txt", "contents");
CopyObjectResult res = s3Client.copyObject("bucket-1", "test.txt", "bucket-2", "folder/test.txt");
```

Exception:
`cannot copy object /bucket-1/test.txt: java.nio.file.NoSuchFileException: /bucket-2/folder/test.txt`

Reason:
`better.files.File.copyTo` that is used for copying objects do not create destination folders automatically. Calling `better.file.File.createIfNotExists(createParents = true)` on destFile may help to solve it.

**Comment by danielytics** [comment]
I've hit the exact same problem :'(

**Comment by shuttie** [comment]
Fixed in https://github.com/findify/s3mock/commit/b8d8be16a87e2b866793142018ea7616c3100ab9
