### ISSUE TITLE
alpakka-s3 is not compatible with s3mock

### ISSUE THREAD

**Issue by shuttie** [findify/s3mock#26]
As alpakka's client has it's own implementation of s3 client protocol, there's no way to setup the endpoint address in a way to be compatible with s3mock. And alpakka always enforces https, which is not yet supported. This bug is not actually s3mock's bug, but a note to myself (Roman Grebennikov) to make PR to alpakka to support non-https custom endpoints.

**Comment by rodricifuentes1** [comment]
This would be a really great feature :)

**Comment by shuttie** [comment]
Alpakka 0.8 works out of the box with s3mock 0.2. I've also added corresponding test cases.
