### ISSUE TITLE
Release to Maven Central in addition to bintray?

### ISSUE THREAD

**Issue by ksclarke** [findify/s3mock#27]
Are you planning to publish to Maven Central too? Maven discourages using third party repositories on poms that are going to be pushed into Central, so it would be nice to be able to use s3mock without having to configure an external repository in my pom.

**Comment by shuttie** [comment]
I've published to maven-central: http://search.maven.org/#search%7Cga%7C1%7Cs3mock
Actually I have not yet updated docs for that, but will do this a bit later.
