### ISSUE TITLE
deleteObjects is not supported

### ISSUE THREAD

**Issue by anaida-gasparyan** [findify/s3mock#32]
Everything is working ok with AmazonS3Client.deleteObject(String bucketName, String key) but it fails when calling AmazonS3Client.deleteObjects(DeleteObjectsRequest deleteObjectRequest) for bulk deletion

**Comment by shuttie** [comment]
Fixed in https://github.com/findify/s3mock/commit/0bbcd90faccdbbe42b8389b5ba5d561a5e3c5c39
