### ISSUE TITLE
ObjectListing#getCommonPrefixes() return empty list

### ISSUE THREAD

**Issue by ksimbv** [findify/s3mock#35]
Expected value of `listing.getCommonPrefixes` is a `List<String>` of 2 common prefixes `dev/someEvent/2016` and `dev/someEvent/2017` but it's returning an empty list when running on s3mock. The same code works fine on an actual S3 instance.

    s3Mock = S3Mock.create(8001, "/tmp/s3");
    s3Mock.start();

    amazonS3Client = new AmazonS3Client();

    amazonS3Client.setEndpoint("http://127.0.0.1:8001");
    amazonS3Client.createBucket("test-bucket");
    amazonS3Client.putObject("test-bucket", "dev/someEvent/2017/03/13/00/_SUCCESS", FILE);
    amazonS3Client.putObject("test-bucket", "dev/someEvent/2017/03/13/01/_SUCCESS", FILE);
    amazonS3Client.putObject("test-bucket", "dev/someEvent/2016/12/31/23/_SUCCESS", FILE);
    amazonS3Client.putObject("test-bucket", "_SUCCESS", FILE);

    ListObjectsRequest listObjectsRequest = new ListObjectsRequest("test-bucket", "dev/", null, "/", null);
    ObjectListing listing = amazonS3Client.listObjects(listObjectsRequest);
    System.out.println("getCommonPrefixes: " + listing.getCommonPrefixes()); //null
    System.out.println("getObjectSummaries: " + listing.getObjectSummaries()); //shows 3 objectSummaries

**Comment by shuttie** [comment]
Should be fixed in https://github.com/findify/s3mock/commit/9b70db673f6b8fe8a5b88f8b60b1f964b688e66c
