### ISSUE TITLE
Unable to write put objects to temp folder in java

### ISSUE THREAD

**Issue by alee-r7** [findify/s3mock#4]
This seems like an issue, but I recently pulled down s3 mock and followed the instructions. However, I'm unable to PUT any objects into my temp folder. It always seems to be writing 0 bytes which eventually fails the md5 of the put method. Below is what I'm seeing in the logs.

07:48:43.445 [sqsmock-akka.actor.default-dispatcher-3] DEBUG i.f.s3mock.provider.FileProvider - writing file for s3://my-bucket/contents to /tmp/s3/mybucket/contents, bytes = 0

Is this expected or am I missing something in the configuration. I tried using anom and a generic basic credential as well.

**Comment by shuttie** [comment]
@alee-r7 can you please provide the example code triggering this behaviour?
