### ISSUE TITLE
S3Mock doesn't differ paths with and without slash at the end

### ISSUE THREAD

**Issue by jimirocks** [findify/s3mock#45]
having stored some object under the key `some/path/example` it should
* respond with 404 on `getObject("some/path")` or `getObject("some/path/")` but it responds with 500
* respond with 204 on `deleteObject("some/path")` and do nothing but it responds with 204 and deletes the keys prefixed with `some/path`
* also now it's not possible to store two objects ie. one with key `key` and the second with key `key/` or `key/example`

... may be some other cases needs to be reconsidered as well

**Comment by jimirocks** [comment]
Investigated more and looks like the behaviour is also different for in memory vs. file provider, at least the file provider doesn't do the wrong delete

**Comment by shuttie** [comment]
I've fixed issues 1 and 2. As for 3, it's more tricky as when using file-based provider (which dumps everything on disk), you cannot have file and subfolder share the same name. POSIX filesystems explicitly do not allow it.
