### ISSUE TITLE
use S3Mock under PowerMock causing issues 

### ISSUE THREAD

**Issue by handtalk** [findify/s3mock#58]
I tried the tutorial example JavaBuilderExample under JUnit4 test:

//@RunWith(PowerMockRunner.class)
public class JavaBuilderExample {
    @Test
    public void testS3() {
//        public static void main(String[] args) {
        S3Mock api = new S3Mock.Builder().withPort(8001).withInMemoryBackend().build();
        api.start();
        AmazonS3 client = AmazonS3ClientBuilder
                .standard()
                .withPathStyleAccessEnabled(true)
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localhost:8001", "us-east-1"))
                .withCredentials(new AWSStaticCredentialsProvider(new AnonymousAWSCredentials()))
                .build();
        client.createBucket("testbucket");
        client.putObject("testbucket", "file/name", "contents");
        api.stop();
    }

}

alone, it works.

But I got errors when using it under PowerMock by uncommenting the line //@RunWith(PowerMockRunner.class)

to the following:

@RunWith(PowerMockRunner.class)
public class JavaBuilderExample {
    @Test
    public void testS3() {
...

the error message is:

java.security.NoSuchAlgorithmException: class configured for KeyManagerFactory: sun.security.ssl.KeyManagerFactoryImpl$SunX509 not a KeyManagerFactory

	at sun.security.jca.GetInstance.checkSuperClass(GetInstance.java:260)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:237)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at javax.net.ssl.KeyManagerFactory.getInstance(KeyManagerFactory.java:137)
	at com.typesafe.sslconfig.ssl.DefaultKeyManagerFactoryWrapper.<init>(SSLContextBuilder.scala:75)

I Google searched, and tried to use annotations:
@RunWith(PowerMockRunner.class)
@PowerMockIgnore("javax.net.ssl.*")
public class JavaBuilderExample {
    @Test
    public void testS3() {

...

and got a different error message:
java.lang.LinkageError: loader constraint violation: loader (instance of org/powermock/core/classloader/MockClassLoader) previously initiated loading for a different type with name "javax/management/MBeanServer"

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at org.powermock.core.classloader.MockClassLoader.loadUnmockedClass(MockClassLoader.java:238)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:182)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:70)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.amazonaws.jmx.MBeans.registerMBean(MBeans.java:52)
	at com.amazonaws.jmx.SdkMBeanRegistrySupport.registerMetricAdminMBean(SdkMBeanRegistrySupport.java:27)
	at com.amazonaws.metrics.AwsSdkMetrics.registerMetricAdminMBean(AwsSdkMetrics.java:392)

Any suggestions to overcome this? I need to use PowerMock to use S3 Mock for unit testing my application.

Thank you.

**Comment by handtalk** [comment]
the class file content is

package com.mydomain.tests3mockr;


import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.AnonymousAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3Builder;
import com.amazonaws.services.s3.AmazonS3Client;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import io.findify.s3mock.S3Mock;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.core.classloader.annotations.PowerMockIgnore;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;


@RunWith(PowerMockRunner.class)
@PowerMockIgnore("javax.net.ssl.*")
public class JavaBuilderExample {
    @Test
    public void testS3() {
//        public static void main(String[] args) {
        S3Mock api = new S3Mock.Builder().withPort(8001).withInMemoryBackend().build();
        api.start();
        AmazonS3 client = AmazonS3ClientBuilder
                .standard()
                .withPathStyleAccessEnabled(true)
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localhost:8001", "us-east-1"))
                .withCredentials(new AWSStaticCredentialsProvider(new AnonymousAWSCredentials()))
                .build();
        client.createBucket("testbucket");
        client.putObject("testbucket", "file/name", "contents");
        api.stop();
    }

}

**Comment by handtalk** [comment]
I solved by the annotation:

@RunWith(PowerMockRunner.class)
@PowerMockIgnore( {"javax.net.ssl.*" ,"javax.management.*"})
public class ExampleTest {
    @Test
    public void testS3() {
        S3Mock api = S3Mock.create(8001, "/tmp/s3");
...

**Comment by shuttie** [comment]
According to an annotation used to fix this issue, there's nothing s3mock can do to help you :)
