### ISSUE TITLE
Wrong content type on GET Service

### ISSUE THREAD

**Issue by effweh-ait** [findify/s3mock#60]
When doing a GET on "/", the returned `ListAllMyBucketsResult` is sent as `text/plain` instead of `application/xml`, which is a fatal error with jets3t:
`org.jets3t.service.S3ServiceException: Expected XML document response from S3 but received content type text/plain; charset=UTF-8`

**Comment by bjethwan** [comment]
I ran into same issue using https://github.com/rest-assured.
Is there a known work-around?

**Comment by bjethwan** [comment]
rest assured worked ...

` EndpointConfiguration endpoint = new EndpointConfiguration("http://localhost:8001", "us-east-1");
	    
		AmazonS3Client client = (AmazonS3Client) AmazonS3ClientBuilder
				.standard()
				.withEndpointConfiguration(endpoint)
				.withPathStyleAccessEnabled(true)  
				.withCredentials(new AWSStaticCredentialsProvider(credentials))     
				.build();

		client.createBucket("bipindelete");
		client.putObject("bipindelete", "foldername/filename.txt", "this is just the sample text for the file content");
		
		//RestAssured.baseURI = "http://localhost:8001";
		RestAssured.port = 8001;
		RestAssured.basePath = "bipindelete";
		RestAssured.registerParser("text/plain", Parser.XML);
			
		get("foldername/filename.txt").then().statusCode(200).body(equalTo("this is just the sample text for the file content"));
		get().then().statusCode(200).body("ListBucketResult.Name", equalTo("bipindelete"));`
