### ISSUE TITLE
What's the best way to write JUnit asserts?

### ISSUE THREAD

**Issue by bjethwan** [findify/s3mock#62]
Say that I use below code to create a bucket, folder, and a file.

`              EndpointConfiguration endpoint = new EndpointConfiguration("http://localhost:8001", "us-east-1");
	    
		AmazonS3Client client = (AmazonS3Client) AmazonS3ClientBuilder
				.standard()
				.withEndpointConfiguration(endpoint)
				.withPathStyleAccessEnabled(true)  
				.withCredentials(new AWSStaticCredentialsProvider(credentials))     
				.build();

		client.createBucket("bipindelete");
		client.putObject("bipindelete", "foldername/filename.txt", "this is just the sample text for the file content");
`

Should I be writing a corresponding S3 Get or simple assert on 
"http://localhost:8001/bipindelete/foldername/filename.txt"????

I have a gut that assert on "http://localhost:8001/bipindelete/foldername/filename.txt" using some HTTP client library would be best...any comments???

**Comment by shuttie** [comment]
There is no single true right way to write assertions. I guess the simplest way will be to use s3 client in a regular way to validate your assertion. But direct HTTP call is also fine.
